/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HairColorService } from "../hairColor.service";
import { HairColorCreateInput } from "./HairColorCreateInput";
import { HairColor } from "./HairColor";
import { HairColorFindManyArgs } from "./HairColorFindManyArgs";
import { HairColorWhereUniqueInput } from "./HairColorWhereUniqueInput";
import { HairColorUpdateInput } from "./HairColorUpdateInput";
import { FeaturesFindManyArgs } from "../../features/base/FeaturesFindManyArgs";
import { Features } from "../../features/base/Features";
import { FeaturesWhereUniqueInput } from "../../features/base/FeaturesWhereUniqueInput";

export class HairColorControllerBase {
  constructor(protected readonly service: HairColorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HairColor })
  async createHairColor(
    @common.Body() data: HairColorCreateInput
  ): Promise<HairColor> {
    return await this.service.createHairColor({
      data: data,
      select: {
        color: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [HairColor] })
  @ApiNestedQuery(HairColorFindManyArgs)
  async hairColors(@common.Req() request: Request): Promise<HairColor[]> {
    const args = plainToClass(HairColorFindManyArgs, request.query);
    return this.service.hairColors({
      ...args,
      select: {
        color: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HairColor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async hairColor(
    @common.Param() params: HairColorWhereUniqueInput
  ): Promise<HairColor | null> {
    const result = await this.service.hairColor({
      where: params,
      select: {
        color: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HairColor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHairColor(
    @common.Param() params: HairColorWhereUniqueInput,
    @common.Body() data: HairColorUpdateInput
  ): Promise<HairColor | null> {
    try {
      return await this.service.updateHairColor({
        where: params,
        data: data,
        select: {
          color: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HairColor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHairColor(
    @common.Param() params: HairColorWhereUniqueInput
  ): Promise<HairColor | null> {
    try {
      return await this.service.deleteHairColor({
        where: params,
        select: {
          color: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/featuresItems")
  @ApiNestedQuery(FeaturesFindManyArgs)
  async findFeaturesItems(
    @common.Req() request: Request,
    @common.Param() params: HairColorWhereUniqueInput
  ): Promise<Features[]> {
    const query = plainToClass(FeaturesFindManyArgs, request.query);
    const results = await this.service.findFeaturesItems(params.id, {
      ...query,
      select: {
        bodyType: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        face: {
          select: {
            id: true,
          },
        },

        hairColor: {
          select: {
            id: true,
          },
        },

        height: true,
        id: true,
        updatedAt: true,
        weight: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/featuresItems")
  async connectFeaturesItems(
    @common.Param() params: HairColorWhereUniqueInput,
    @common.Body() body: FeaturesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featuresItems: {
        connect: body,
      },
    };
    await this.service.updateHairColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/featuresItems")
  async updateFeaturesItems(
    @common.Param() params: HairColorWhereUniqueInput,
    @common.Body() body: FeaturesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featuresItems: {
        set: body,
      },
    };
    await this.service.updateHairColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/featuresItems")
  async disconnectFeaturesItems(
    @common.Param() params: HairColorWhereUniqueInput,
    @common.Body() body: FeaturesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featuresItems: {
        disconnect: body,
      },
    };
    await this.service.updateHairColor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
