/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FaceService } from "../face.service";
import { FaceCreateInput } from "./FaceCreateInput";
import { Face } from "./Face";
import { FaceFindManyArgs } from "./FaceFindManyArgs";
import { FaceWhereUniqueInput } from "./FaceWhereUniqueInput";
import { FaceUpdateInput } from "./FaceUpdateInput";
import { FeaturesFindManyArgs } from "../../features/base/FeaturesFindManyArgs";
import { Features } from "../../features/base/Features";
import { FeaturesWhereUniqueInput } from "../../features/base/FeaturesWhereUniqueInput";

export class FaceControllerBase {
  constructor(protected readonly service: FaceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Face })
  async createFace(@common.Body() data: FaceCreateInput): Promise<Face> {
    return await this.service.createFace({
      data: {
        ...data,

        image: data.image
          ? {
              connect: data.image,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Face] })
  @ApiNestedQuery(FaceFindManyArgs)
  async faces(@common.Req() request: Request): Promise<Face[]> {
    const args = plainToClass(FaceFindManyArgs, request.query);
    return this.service.faces({
      ...args,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Face })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async face(
    @common.Param() params: FaceWhereUniqueInput
  ): Promise<Face | null> {
    const result = await this.service.face({
      where: params,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Face })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFace(
    @common.Param() params: FaceWhereUniqueInput,
    @common.Body() data: FaceUpdateInput
  ): Promise<Face | null> {
    try {
      return await this.service.updateFace({
        where: params,
        data: {
          ...data,

          image: data.image
            ? {
                connect: data.image,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Face })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFace(
    @common.Param() params: FaceWhereUniqueInput
  ): Promise<Face | null> {
    try {
      return await this.service.deleteFace({
        where: params,
        select: {
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/featuresItems")
  @ApiNestedQuery(FeaturesFindManyArgs)
  async findFeaturesItems(
    @common.Req() request: Request,
    @common.Param() params: FaceWhereUniqueInput
  ): Promise<Features[]> {
    const query = plainToClass(FeaturesFindManyArgs, request.query);
    const results = await this.service.findFeaturesItems(params.id, {
      ...query,
      select: {
        bodyType: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        face: {
          select: {
            id: true,
          },
        },

        hairColor: {
          select: {
            id: true,
          },
        },

        height: true,
        id: true,
        updatedAt: true,
        weight: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/featuresItems")
  async connectFeaturesItems(
    @common.Param() params: FaceWhereUniqueInput,
    @common.Body() body: FeaturesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featuresItems: {
        connect: body,
      },
    };
    await this.service.updateFace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/featuresItems")
  async updateFeaturesItems(
    @common.Param() params: FaceWhereUniqueInput,
    @common.Body() body: FeaturesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featuresItems: {
        set: body,
      },
    };
    await this.service.updateFace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/featuresItems")
  async disconnectFeaturesItems(
    @common.Param() params: FaceWhereUniqueInput,
    @common.Body() body: FeaturesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featuresItems: {
        disconnect: body,
      },
    };
    await this.service.updateFace({
      where: params,
      data,
      select: { id: true },
    });
  }
}
